const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const output=path.resolve('..','institute-preview');
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || 'chrome'});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.argv[2]);
  await page.waitForSelector('[data-institute-select]');
  assert(await page.locator('#clinicLanding').isVisible(),'Institutes shares the homepage account selection');
  assert(await page.locator('#instituteAccounts').isVisible(),'Institute cards are selected on entry');
  assert(await page.locator('#clinicAccounts').isHidden(),'Clinic cards must not mix with institute cards');
  const hero = await page.locator('.landingHero').boundingBox();
  await page.getByRole('tab',{name:'Clínicas',exact:true}).click();
  assert(await page.locator('#clinicAccounts').isVisible());
  assert(await page.locator('#instituteAccounts').isHidden());
  await page.waitForSelector('[data-clinic-card="vielle"]:visible');
  await page.screenshot({path:path.join(output,'workspace-clinics.png'),fullPage:true});
  await page.getByRole('tab',{name:'Institutos',exact:true}).click();
  assert.deepEqual(await page.locator('.landingHero').boundingBox(),hero,'Header must not move when changing areas');
  await page.getByRole('tab',{name:'Institutos',exact:true}).press('ArrowLeft');
  assert.equal(await page.getByRole('tab',{name:'Clínicas',exact:true}).getAttribute('aria-selected'),'true');
  await page.getByRole('tab',{name:'Clínicas',exact:true}).press('ArrowRight');
  await page.screenshot({path:path.join(output,'institutes-selection.png'),fullPage:true});
  await page.locator('[data-institute-select="victor-paranhos"]').click();
  await page.waitForSelector('.kpi');
  const month=(await page.locator('#from').inputValue()).slice(0,8);
  await page.locator('#to').fill(month+'28');
  await page.locator('#filters button').click();
  await page.waitForFunction(()=>document.querySelector('#kpis').textContent.includes('240'));
  await page.screenshot({path:path.join(output,'institutes-desktop.png'),fullPage:true});
  const canvas=await page.locator('#revenueChart').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let nonblank=0;for(let i=3;i<d.length;i+=4)if(d[i])nonblank++;return nonblank;});
  assert(canvas>1000,'Revenue canvas must render real pixels');
  await page.locator('[data-tab=leads]').click();await page.waitForSelector('#leadsTable table');
  assert(await page.locator('#campaignTable').textContent().then(t=>t.includes('ROAS')));
  await page.locator('[data-tab=sales]').click();await page.waitForSelector('#ordersTable table');
  await page.locator('#orderStatus').selectOption('waiting_payment');
  await page.waitForFunction(()=>document.querySelector('#ordersPages').textContent.includes('19 registros'));
  await page.locator('[data-tab=integrations]').click();await page.waitForSelector('#courseForm input[name=name]');
  await page.waitForFunction(()=>document.querySelector('#courseForm input[name=name]').value.includes('REGEN'));
  await page.screenshot({path:path.join(output,'institutes-settings.png'),fullPage:true});
  await page.locator('[data-tab=overview]').click();await page.waitForSelector('.kpi');
  const mobile=await browser.newPage({viewport:{width:390,height:844}});
  mobile.on('pageerror',e=>errors.push(e.message));
  await mobile.goto(process.argv[2]);await mobile.waitForSelector('[data-institute-select]');
  await mobile.screenshot({path:path.join(output,'institutes-selection-mobile.png'),fullPage:true});
  await mobile.locator('[data-institute-select="victor-paranhos"]').click();await mobile.waitForSelector('.kpi');
  await mobile.screenshot({path:path.join(output,'institutes-mobile.png'),fullPage:true});
  await mobile.screenshot({path:path.join(output,'institutes-mobile-viewport.png')});
  assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'No mobile horizontal overflow');
  const mobileCanvas=await mobile.locator('#revenueChart').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let pixels=0;for(let i=3;i<d.length;i+=4)if(d[i])pixels++;return pixels;});
  assert(mobileCanvas>1000,'Mobile chart must render real pixels');
  await page.locator('#definitions').click();assert(await page.locator('#definitionsDialog').isVisible());
  await page.locator('#definitionsDialog [data-close]').click();
  await page.locator('#switchInstitute').click();await page.waitForSelector('#instituteAccounts:visible');
  assert.equal(new URL(page.url()).searchParams.get('area'),'institutes');
  assert.equal(new URL(page.url()).searchParams.has('institute'),false,'Returning to selection removes the course scope');
  const home = new URL('/?area=clinics',page.url()).href;
  const restrictedContext = await browser.newContext({storageState:await page.context().storageState()});
  const restricted = await restrictedContext.newPage();
  restricted.on('pageerror',e=>errors.push(e.message));
  await restricted.route('**/api/auth/me',async route=>{
    const response = await route.fetch(), data = await response.json();
    data.clinics = data.clinics.filter(clinic=>clinic.key==='inspire');
    await route.fulfill({response,json:data});
  });
  await restricted.goto(home);
  await restricted.waitForSelector('[data-clinic-card="inspire"]:visible');
  assert(await restricted.locator('[data-clinic-card="vielle"]').isHidden(),'Only permitted clinic cards remain visible');
  assert(await restricted.locator('#dashboardShell').isHidden(),'An explicit home selection must not auto-enter the sole clinic');
  await restricted.getByRole('tab',{name:'Institutos',exact:true}).click();
  await restricted.waitForSelector('[data-institute-select]');
  await restricted.reload();await restricted.waitForSelector('#instituteAccounts:visible');
  assert(await restricted.locator('#clinicAccounts').isHidden(),'Reload preserves institute selection, even with one clinic');
  await restricted.route(/\/api\/institutes$/,route=>route.fulfill({json:{ok:true,institutes:[]}}));
  await restricted.reload();
  await restricted.waitForFunction(()=>document.querySelector('#instituteAccessState').textContent.includes('Nenhum instituto'));
  assert.equal(await restricted.locator('[data-institute-select]').count(),0,'No forbidden institutes or stale cards');
  await restricted.unroute(/\/api\/institutes$/);
  let failures = 1;
  await restricted.route(/\/api\/institutes$/,async route=>{
    if(failures-- > 0) await route.fulfill({status:503,json:{ok:false}});
    else await route.continue();
  });
  await restricted.reload();await restricted.waitForSelector('#retryInstituteAccess:visible');
  await restricted.locator('#retryInstituteAccess').click();await restricted.waitForSelector('[data-institute-select]');
  await restrictedContext.close();
  assert.deepEqual(errors,[]);
  console.log('Institute selection, hierarchy, desktop, mobile, charts, tabs, filters, settings and help: OK');
 }finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exit(1)});
